### ISSUE TITLE
Kurulum yapılamıyor.

### ISSUE THREAD

**Issue by toreador34** [worlds/mutasyon#3]
sub.sitem.com/install urlsine girdiğimde otomatik indexe atıyo. Kurulum yapamıyorum.

Başta database bağlantısı kurmaya çalışıyodu. Doğru db bilgilerini girdim ama bir şey değişmedi. 

Kurulum için sub.sitem.com/install urlsine girmeye çalıştığımda indexe attığı için kurulum adımlarını göremiyorum dolayısıyla takip edemiyorum.

**Comment by toreador34** [comment]
ana dizindeki configs klasöründe db.php dosyası kalmış o yüzden kurulu olduğunu sanarak indexe atıyomuş. Onu silersen çözülür.

**Comment by worlds** [comment]
Özür dilerim geç fark ettim mesajınızı ama çözmüşsünüz zaten :)
