### ISSUE TITLE
Yazılım hangi lisansa sahip?

### ISSUE THREAD

**Issue by bugra9** [worlds/mutasyon#7]
Merhaba,

Herhangi bir lisans belirtmemişsiniz dolayısıyla yazılımın özgür olup olmadığını anlayamıyorum. Mümkünse lisans dosyasını ekleyebilir misiniz?

**Comment by worlds** [comment]
Haklisiniz eklemeyi unutmuşum. Mutasyon tamamen ücretsizdir ve gpl v3 lisansı altında dağıtılıyor

**Comment by bugra9** [comment]
Cevap için teşekkürler.
